---
title: "室友的貓走了"
lang: zh-TW
date: 2026-07-23
author: Anthony
categories: [生活]
description: "懼怕的並不是死亡本身，是離開，離開我這個人。"
---

室友的貓走了。

很突然地走了。沒有生病、沒有任何意外。就這樣走了。

我很討厭這種感覺，除了悲傷，更多的是懼怕。

懼怕的並不是死亡本身，是離開，離開我這個人。

這讓我想起在我碩一那年，外公因為在家裡跌倒，撞到前額，原本以為不是什麼大事，他也蠻健康的。沒想到事情在兩個禮拜後發生巨大的轉變。首先是他突然間開始失憶，忘記很多東西，不過還是可以自理一些生活瑣事。我媽帶他去看醫生，醫生說傷到記憶的區塊，聽到當下真的不知所措，一方面是「怎麼會這樣」，另一方面是「為什麼當初不送去醫院」。

不過說後悔也來不及了。

於是外公就被送到家裡附近的長照中心托人照顧。

原以為只是單純的養傷，過一陣子就會恢復記憶，沒想到在有一次我去看他時，他用台語問我：

「吟甄（我媽的小名）呢？」
「她在上班啊，你想見她喔？」

回完這句話，外公沈默了一陣。

「我想回家。」

當下我只能跟他說過幾天就可以回去啦，忍耐一下好不好。身上插著鼻胃管的他，又再跟我說一次，他想回家。

我也不知道該怎麼回下去了，我只知道如果我繼續待在那邊，可能沒辦法承受。所以我就跟他打哈哈轉移其他話題。

聊了一陣子之後，我就準備回去。離開前我跟護理人員說了剛剛的事情，他們回覆我會再觀察看看的。

又隔了一陣子，我再去看他，這次他睡著了，沒有醒著。

我就靜靜地坐在他旁邊，自顧自地跟他說話，心裡似乎也不在乎他到底能不能聽見了。

外公的狀況越來越糟糕，被送到另一個，我只能說是「等死」的安養中心，那邊的環境比原本的看護中心更糟，倒不至於髒亂，但每次去看外公時，總覺得瀰漫著一股死亡的氣息。

只是從這之後，每次去看他時，他沒有一次是醒著的，看護將他抱上輪椅推出來後，我（有時是我跟我媽）也是不知道該跟他說些什麼，我媽時不時會跟他說「知道我是誰嗎？」、「我們來看你囉！」但得到的回覆都是沈默。

「阿公過世了。」

那是一個陰天，當天我在中研院擔任研究助理的工作。看到訊息時，我似乎有種莫名的冷靜，但手卻不自覺地發抖。

隔了約10幾分鐘後，我跑去找老師，跟老師說家中有急事，需要先回去一趟。然後我就拿著安全帽騎車衝回去。

不過在騎到一半的時候，我媽打給我，先別回來。我也沒有問她為什麼，我就說好。於是我只能先回到租屋處。

回到租屋處，我什麼話都沒說，女友問我怎麼了我什麼話也不講，就是坐在那邊。

隔了一陣，我才緩緩開口跟我女友說明情況。

她似乎也察覺到當時再多說什麼也對我沒有幫助，只是抱了抱我，什麼都沒有說，就留我一個人靜一靜。

當天晚上，我參加了一場線上的讀書會，我只記得是政治幾何學的讀書會，但讀書會的內容，我是一個字都不記得。讀書會報告完之後我就匆匆下線，陪我女友去買東西。

回到租屋處後，我癱坐在房間的地方，放聲大哭。倒也沒有哭的撕心裂肺，只是我女友在我旁邊說安慰的話我是一個字都沒聽進去。

接著我就跟我女友說謝謝，道個別，騎車回我家了。

到家後，我也什麼都沒說，洗個澡就睡去。

不知道過了多久，聽到鳥鳴聲。早上了。

我起床、換個衣服，坐在書桌前發呆，也不知道在想什麼。那幾天的生活大概都是這樣，直到外公出殯那天，為他送行，看到他本就不豐腴的臉消瘦地像骷顱，心中雖然覺得難過，但似乎也在外公被推入火葬場後，轉為釋懷。

現在回想起來，或許是因為這是我人生第一次面對至親離世，沒有辦法接受的反應。

我從搬來到祂過世的時候，認識了這隻貓已有近五年的時間，也算是把祂視為家人。

這幾天翻了照片，翻著翻著就哭了。看到照片就會懷念跟祂玩的時候，還有半夜我在趕工時，室友們跟女友都睡了，只有祂還醒著陪我。

這個感覺又再次襲來，很不舒服，但也只能選擇接受。

人生中總有生離死別，但知道跟能夠接受是兩碼子事。也許我該學著如何面對這一切，又或者是，隨著感覺走，我也不曉得，一切都交由命運安排⋯
