---
title: "Python 教學系列: Python 簡介與安裝"
lang: zh-TW
date: 2026-04-13
author: Anthony
categories: [Python, 程式設計]
description: "從零開始接觸 Python"
# image: images/LaTeX_logo.svg
---

在撰寫此篇文章的 2026，Python 依舊是全球最受歡迎、最廣受使用的語言。根據 [IEEE 科技縱覽](https://spectrum.ieee.org/top-programming-languages-2025) 在 2025 年的統計，無論從綜合排名、長期趨勢以及職缺的角度，Python 都位居第一，緊追其後的則是老語言 C/C++ 與 Java。

<details>
<summary>2025 程式語言排名（IEEE Spectrum）</summary>
<div style="display: flex; justify-content: center;">
<iframe scrolling="no" frameborder="0" title="Interactive or visual content" sandbox="allow-same-origin allow-forms allow-scripts allow-downloads allow-popups allow-popups-to-escape-sandbox allow-top-navigation-by-user-activation" style="width: 70%; height: 1776.58px;" src="https://flo.uri.sh/visualisation/24825595/embed?auto=1"></iframe>
</div>
</details>

從資料分析、人工智慧、自動化腳本到後端網頁開發，Python 可謂無處不在。然而，網路上的教學資源雖然豐富，卻存在一個巨大的斷層：**基礎語法與工程實戰之間的距離**。許多人學會了流程控制，甚至可以自己寫一個小程式在本地運行，但當他們打開一個專業的開源專案時，卻被滿屏的型別標注、裝飾器或是複雜的專案管理套件搞得一頭霧水。這就是為什麼我決定寫這個系列——不只教你寫出能跑的程式，更要教你寫出專業、優雅且可維護的程式碼，以及分享我曾經踩過的坑。

## 系列介紹

**Python 教學系列**並非一套傳統的語法字典。在規劃這個系列時，我設定了幾個核心準則，並貫穿未來所有的文章：

1. 以**工程化**為起點：本系列所有的範例與專案，都會建立在專案結構之上。在學校或是外面的課程，你可能都聽過虛擬環境管理，但並不知道虛擬環境的用途，甚至不太了解它的重要性。因此本系列會從建立虛擬環境開始，一步步奠定基礎。

2. 全面擁抱**型別標註**：Python 雖然是動態型別語言，但在現代開發中，沒有型別標註的程式碼被視為一種技術債。從第一章開始，我們就會強制引入型別宣告。這不僅能大幅減少 Bug，還能讓你的編輯器提供神級的自動補完與錯誤偵測。

3. 深入 Python 內建標準庫：許多 Python 遇到問題的第一反應是安裝第三方套件，但其實 Python 內建的標準庫已經強大到令人折服。我們會深入探討 Python 內建的工具，教你如何用最少的依賴完成最多的任務。

## 系列緣起

實不相瞞，這套系列也是寫給我自己的。

程式開發是一個不進則退的領域。隨著 Python 版本不斷更新[^1]，許多舊習慣已經被更安全、更高效的新語法取代。透過整理這些內容，在教學時也幫自己進行一次全面的知識體系複習。

## 給讀者的建議

如果你是初學者，請不要只看程式碼，一定要動手跟著寫。

Python 的哲學之一是[^2]：

> *There should be one-- and preferably only one --obvious way to do it.*

這個系列的目的，就是帶你找到那種「最明顯、最正確、最優雅」的方法。


[^1]: 撰文時間為 2026/04/13，最新版本為 `3.14.4`，請以[官方](https://www.python.org/downloads/)發佈為主。
[^2]: 詳見 [Python 之禪 (The Zen of Python)](https://peps.python.org/pep-0020/#the-zen-of-python)。只要在 Python 解釋器（互動式環境）中輸入以下指令：
    ```python
    import this
    ```
    程式碼會輸出由 [Tim Peters](https://en.wikipedia.org/wiki/Tim_Peters_(software_engineer)) (Python 程式語言的核心貢獻者) 編寫的 19 條核心 Python 設計原則，強調簡單、清晰和可讀性